apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  labels:
    component: elasticsearch
    role: client
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/_prometheus/metrics'
    prometheus.io/port: '9200'
spec:
  selector:
    component: elasticsearch
    role: client
  ports:
  - port: 9200
    protocol: TCP
